{% set name = "jaxsim" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxsim-{{ version }}.tar.gz
  sha256: e7567eb267e9c0d7ea3def4aa4176166e143006984eedc2d76c1339e415c568a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    # From build-system.requires:
    - wheel
    - setuptools >=64
    - setuptools-scm >=8
  run:
    # Main dependencies:
    - python >=3.10
    - coloredlogs
    - jax >=0.4.13
    - jaxlib >=0.4.13
    - jaxlie >=1.3.0
    - jax-dataclasses >=1.4.0
    - pptree
    - rod >=0.3.0
    - typing-extensions
    # Extra [viz] dependencies:
    - lxml
    - mediapy
    - mujoco >=3.0.0

test:
  imports:
    - jaxsim
  commands:
    - pip check
    - test "$(pip list | grep jaxsim | awk '{print $2}')" == "$PKG_VERSION"
  requires:
    - pip

about:
  home: https://github.com/ami-iit/jaxsim
  summary: A differentiable physics engine and multibody dynamics library for control and robot learning.
  dev_url: https://github.com/ami-iit/jaxsim
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flferretti
    - diegoferigo
    - traversaro
