{% set name = "jaxsim" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxsim-{{ version }}.tar.gz
  sha256: f929d01fb6595e4702457fc922c5a1f6e49e20370491b5ebb7d4fa7c031d5055

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - wheel
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - typing-extensions
    - python >=3.11
    - coloredlogs
    - jax >=0.4.13
    - jaxlib >=0.4.13
    - jaxlie >=1.3.0
    - jax-dataclasses >=1.4.0
    - lxml
    - mediapy
    - mujoco >=3.0.0
    - pptree
    - rod >=0.3.0

test:
  imports:
    - jaxsim
  commands:
    - pip check
    - test "$(pip list | grep jaxsim | awk '{print $2}')" == "$PKG_VERSION"
  requires:
    - pip

about:
  home: https://github.com/ami-iit/jaxsim
  summary: A physics engine in reduced coordinates implemented with JAX.
  dev_url: https://github.com/ami-iit/jaxsim
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flferretti
    - diegoferigo
    - traversaro
